# Generated by Django 3.1.12 on 2021-08-23 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_compo', models.CharField(max_length=50)),
                ('val', models.CharField(max_length=50)),
                ('style', models.CharField(max_length=50)),
                ('nodes', models.CharField(default='systems', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Thank you', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PageCompoMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=100)),
                ('compo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djAssignment.compo')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djAssignment.page')),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='component',
            field=models.ManyToManyField(through='djAssignment.PageCompoMap', to='djAssignment.Compo'),
        ),
    ]
