# Generated by Django 3.1.12 on 2021-08-21 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djAssignment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compo',
            old_name='type',
            new_name='type_of_compo',
        ),
        migrations.RemoveField(
            model_name='page',
            name='compo',
        ),
        migrations.CreateModel(
            name='PageCompoMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=100)),
                ('compo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djAssignment.compo')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djAssignment.page')),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='compo',
            field=models.ManyToManyField(through='djAssignment.PageCompoMap', to='djAssignment.Compo'),
        ),
    ]
