# Generated by Django 3.1.12 on 2021-08-23 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djAssignment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compo',
            name='pageAssigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djAssignment.page'),
        ),
    ]
