# Generated by Django 3.1.12 on 2021-08-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djAssignment', '0002_auto_20210826_0820'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='page',
            constraint=models.UniqueConstraint(fields=('section', 'name'), name='uniquePages'),
        ),
    ]
