# Generated by Django 3.1.12 on 2021-08-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djAssignment', '0002_auto_20210821_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='name',
            field=models.CharField(default='welcome', max_length=50),
        ),
    ]
