# Generated by Django 3.1.12 on 2021-08-23 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djAssignment', '0002_compo_pageassigned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagecompomap',
            old_name='prefix',
            new_name='date',
        ),
    ]
