# Generated by Django 3.1.12 on 2021-08-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djAssignment', '0003_auto_20210823_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecompomap',
            name='time_field',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
