# Generated by Django 3.1.12 on 2021-08-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djAssignment', '0003_page_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='sections',
        ),
        migrations.AddField(
            model_name='compo',
            name='nodes',
            field=models.CharField(default='systems', max_length=50),
        ),
    ]
