# Generated by Django 3.1.12 on 2021-08-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djAssignment', '0004_auto_20210826_1431'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='compo',
            name='uniqueComponentss',
        ),
        migrations.AddConstraint(
            model_name='compo',
            constraint=models.UniqueConstraint(fields=('type_of_compo', 'val', 'style'), name='uniqueComponents'),
        ),
    ]
