# Generated by Django 3.1.12 on 2021-08-25 07:20

import djAssignment.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('djAssignment', '0005_auto_20210825_0702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_compo', models.CharField(choices=[('ic', 'icons'), ('im', 'image'), ('h', 'heading'), ('b', 'body'), ('l', 'link')], max_length=50, validators=[djAssignment.models.validate_type_of_icons])),
                ('val', models.CharField(max_length=50)),
                ('style', models.CharField(max_length=50)),
                ('nodes', models.CharField(default='systems', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('section', models.IntegerField()),
                ('name', models.CharField(default='Thank you', max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PageCompoMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('time_field', models.TimeField(blank=True, null=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djAssignment.compo')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djAssignment.page')),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='component',
            field=models.ManyToManyField(through='djAssignment.PageCompoMap', to='djAssignment.Compo'),
        ),
        migrations.AddField(
            model_name='compo',
            name='pageAssigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djAssignment.pagecompomap'),
        ),
    ]
